/*******************************************************************************************************************
 * Authors:   SanAndreasP
 * Copyright: SanAndreasP
 * License:   Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
 *                http://creativecommons.org/licenses/by-nc-sa/4.0/
 *******************************************************************************************************************/
package de.sanandrew.mods.varietychests.util;

import cpw.mods.fml.client.registry.ClientRegistry;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;
import de.sanandrew.core.manpack.util.SAPUtils;
import de.sanandrew.mods.varietychests.block.BlockCustomChest;
import de.sanandrew.mods.varietychests.client.ItemRendererCustomChest;
import de.sanandrew.mods.varietychests.client.TileEntityCustomChestRenderer;
import de.sanandrew.mods.varietychests.item.ItemBlockCustomChest;
import de.sanandrew.mods.varietychests.tileentity.TileEntityCustomChest;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.MinecraftForgeClient;
import net.minecraftforge.common.config.Configuration;

@Mod(modid = VarietyChests.MODID, version = VarietyChests.VERSION, name = "Variety Chests")
public final class VarietyChests
{
    public static final String MODID = "varietychests";
    public static final String VERSION = "1.0.0";

    public static final String NBT_CHEST_TYPE = "chestType";

    public static Block customChest;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        event.getModMetadata().autogenerated = false;
        ModConfig.configuration = new Configuration(event.getSuggestedConfigurationFile(), "1.0");
        ModConfig.syncConfig();

        customChest = new BlockCustomChest();
        customChest.setBlockName(MODID + ":customChest");

        SAPUtils.registerBlockWithItem(customChest, ItemBlockCustomChest.class);

        GameRegistry.registerTileEntity(TileEntityCustomChest.class, MODID + ":customChestTE");

        ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomChest.class, new TileEntityCustomChestRenderer());
        MinecraftForgeClient.registerItemRenderer(Item.getItemFromBlock(customChest), new ItemRendererCustomChest());

        this.registerChestTypes();
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {

    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent event) {
        ChestType.registerRecipes();
    }

    private void registerChestTypes() {
        ChestType.registerChestType("spruce", new ResourceLocation(MODID, "textures/entity/chest/spruce.png"),
                                    new ResourceLocation(MODID, "textures/entity/chest/spruce_double.png"),
                                    new ItemStack(Blocks.planks, 1, 1)
        );
        ChestType.registerChestType("birch", new ResourceLocation(MODID, "textures/entity/chest/birch.png"),
                                    new ResourceLocation(MODID, "textures/entity/chest/birch_double.png"),
                                    new ItemStack(Blocks.planks, 1, 2)
        );
        ChestType.registerChestType("jungle", new ResourceLocation(MODID, "textures/entity/chest/jungle.png"),
                                    new ResourceLocation(MODID, "textures/entity/chest/jungle_double.png"),
                                    new ItemStack(Blocks.planks, 1, 3)
        );
        ChestType.registerChestType("acacia", new ResourceLocation(MODID, "textures/entity/chest/acacia.png"),
                                    new ResourceLocation(MODID, "textures/entity/chest/acacia_double.png"),
                                    new ItemStack(Blocks.planks, 1, 4)
        );
        ChestType.registerChestType("darkoak", new ResourceLocation(MODID, "textures/entity/chest/darkoak.png"),
                                    new ResourceLocation(MODID, "textures/entity/chest/darkoak_double.png"),
                                    new ItemStack(Blocks.planks, 1, 5)
        );
    }
}
