/*******************************************************************************************************************
 * Authors:   SanAndreasP
 * Copyright: SanAndreasP
 * License:   Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
 *                http://creativecommons.org/licenses/by-nc-sa/4.0/
 *******************************************************************************************************************/
package de.sanandrew.addons.exblvarietychests.util;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import de.sanandrew.mods.varietychests.util.ChestType;
import extrabiomes.api.Stuff;
import extrabiomes.module.fabrica.block.BlockCustomWood.BlockType;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;

@Mod(modid = ExBiomesXlVarietyChests.MOD_ID, version = ExBiomesXlVarietyChests.VERSION, name = "Variety Chests EXBL AddOn",
     dependencies = "required-after:varietychests@[1.1.1,);required-after:ExtrabiomesXL")
public final class ExBiomesXlVarietyChests
{
    public static final String MOD_ID = "exblvarchests";
    public static final String VERSION = "1.0.0";
//    public static final String PROXY_CLIENT = "de.sanandrew.mods.varietychests.client.util.ClientProxy";
//    public static final String PROXY_SERVER = "de.sanandrew.mods.varietychests.util.CommonProxy";

//    public static final String NBT_CHEST_TYPE = "chestType";

//    public static Block customChest;
//    public static Block customGlowingChest;

    @Instance(MOD_ID)
    public static ExBiomesXlVarietyChests instance;

//    @SidedProxy(clientSide = PROXY_CLIENT, serverSide = PROXY_SERVER, modId = MOD_ID)
//    public static CommonProxy proxy;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
//        event.getModMetadata().autogenerated = false;
//        ModConfig.configuration = new Configuration(event.getSuggestedConfigurationFile(), "1.0");
//        ModConfig.syncConfig();

//        customChest = new BlockCustomChest();
//        customChest.setBlockName(MOD_ID + ":customChest")
//                   .setHardness(2.5F)
//                   .setHarvestLevel("axe", -1);
//
//        customGlowingChest = new BlockCustomGlowingChest();
//        customGlowingChest.setBlockName(MOD_ID + ":customGlowingChest")
//                          .setHardness(2.5F)
//                          .setHarvestLevel("axe", -1);

//        SAPUtils.registerBlockWithItem(customChest, ItemBlockCustomChest.class);
//        SAPUtils.registerBlockWithItem(customGlowingChest, ItemBlockCustomChest.class);
//
//        GameRegistry.registerTileEntity(TileEntityCustomChest.class, MOD_ID + ":customChestTE");
//
//        proxy.modPreInit();

//        OreDictionary.registerOre("chestWood", customChest);
//        OreDictionary.registerOre("chestWood", customGlowingChest);

        registerChestTypes();
    }

    @EventHandler
    @SuppressWarnings("unchecked")
    public void postInit(FMLPostInitializationEvent event) {
//        RecipeSorter.register(ExBiomesXlVarietyChests.MOD_ID + ":recipe_cchest", RecipeNormalChests.class, Category.SHAPED, "after:minecraft:shaped");
//        RecipeSorter.register(ExBiomesXlVarietyChests.MOD_ID + ":recipe_glowcchest", RecipeGlowingChests.class, Category.SHAPELESS, "after:minecraft:shapeless");
//
//        CraftingManager.getInstance().getRecipeList().add(new RecipeNormalChests());
//        CraftingManager.getInstance().getRecipeList().add(new RecipeGlowingChests());
    }

    private static void registerChestTypes() {
        ChestType.registerChestType("redwood", new ResourceLocation(MOD_ID, "textures/entity/chest/redwood.png"),
                                    new ResourceLocation(MOD_ID, "textures/entity/chest/redwood_double.png"),
                                    new ItemStack(Stuff.planks.get(), 1, BlockType.REDWOOD.metadata())
        );
        ChestType.registerChestType("fir", new ResourceLocation(MOD_ID, "textures/entity/chest/fir.png"),
                                    new ResourceLocation(MOD_ID, "textures/entity/chest/fir_double.png"),
                                    new ItemStack(Stuff.planks.get(), 1, BlockType.FIR.metadata())
        );
        ChestType.registerChestType("acacia_exbl", new ResourceLocation(MOD_ID, "textures/entity/chest/acacia_exbl.png"),
                                    new ResourceLocation(MOD_ID, "textures/entity/chest/acacia_exbl_double.png"),
                                    new ItemStack(Stuff.planks.get(), 1, BlockType.ACACIA.metadata())
        );
        ChestType.registerChestType("cypress", new ResourceLocation(MOD_ID, "textures/entity/chest/cypress.png"),
                                    new ResourceLocation(MOD_ID, "textures/entity/chest/cypress_double.png"),
                                    new ItemStack(Stuff.planks.get(), 1, BlockType.CYPRESS.metadata())
        );
        ChestType.registerChestType("japanesemaple", new ResourceLocation(MOD_ID, "textures/entity/chest/japanesemaple.png"),
                                    new ResourceLocation(MOD_ID, "textures/entity/chest/japanesemaple_double.png"),
                                    new ItemStack(Stuff.planks.get(), 1, BlockType.JAPANESE_MAPLE.metadata())
        );
        ChestType.registerChestType("rainboweucalyptus", new ResourceLocation(MOD_ID, "textures/entity/chest/rainboweucalyptus.png"),
                                    new ResourceLocation(MOD_ID, "textures/entity/chest/rainboweucalyptus_double.png"),
                                    new ItemStack(Stuff.planks.get(), 1, BlockType.RAINBOW_EUCALYPTUS.metadata())
        );
        ChestType.registerChestType("autumn", new ResourceLocation(MOD_ID, "textures/entity/chest/autumn.png"),
                                    new ResourceLocation(MOD_ID, "textures/entity/chest/autumn_double.png"),
                                    new ItemStack(Stuff.planks.get(), 1, BlockType.AUTUMN.metadata())
        );
        ChestType.registerChestType("baldcypress", new ResourceLocation(MOD_ID, "textures/entity/chest/baldcypress.png"),
                                    new ResourceLocation(MOD_ID, "textures/entity/chest/baldcypress_double.png"),
                                    new ItemStack(Stuff.planks.get(), 1, BlockType.BALD_CYPRESS.metadata())
        );
        ChestType.registerChestType("sakura", new ResourceLocation(MOD_ID, "textures/entity/chest/sakura.png"),
                                    new ResourceLocation(MOD_ID, "textures/entity/chest/sakura_double.png"),
                                    new ItemStack(Stuff.planks.get(), 1, BlockType.SAKURA_BLOSSOM.metadata())
        );
    }
}
